steps:
  #builds the container image.
  - name: 'gcr.io/cloud-builders/docker'
    id: Build image
    args:
      - 'build'
      - '-f'
      - 'devops/dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/uno-back:$SHORT_SHA-$BUILD_ID'
      - '.'

  # pushes the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/uno-back:$SHORT_SHA-$BUILD_ID'

  # replace values on configmap with the matched vars in gcp trigger
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Replace vars
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        sed -i 's/_VAR_TEST/${_VAR_TEST}/' devops/k8s/uno-back-config-map.yaml

  