steps:
  #builds the container image.
  - name: 'gcr.io/cloud-builders/docker'
    id: Build image
    args:
      - 'build'
      - '-f'
      - 'devops/dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/uno-back:$SHORT_SHA-$BUILD_ID'
      - '.'

  # pushes the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/uno-back:$SHORT_SHA-$BUILD_ID'

  # replace values on configmap with the matched vars in gcp trigger
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'devops/k8s/uno-back-config-map.yaml'
      - '-n'
      - 'staging'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=southamerica-east1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=uno-cluster-1'
      - '_VAR_TEST=$_VAR_TEST'