name: CI - Uno Back - Node - Quality Check

on:
  pull_request:
    branches:
    - main

jobs:
  quality: 
    name: Test on Node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
      
    strategy:
      matrix:
        node_version: ['16']
        os: [ubuntu-latest]
        
        
    steps:
    - name: Git Checkout
      uses: actions/checkout@v1
      
    - name: Use Node.js VERSION ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node-version }}
      
    - name: Install dependences
      run: yarn
      
    - name: Run unit tests
      run: yarn test

    - name: Build test
      run: yarn build
